# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCq6c7y9l7uJJZIYpIZGAMv3WpupZIuI
"""

import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime

def load_data(file):
    df = pd.read_csv(file, infer_datetime_format=True, parse_dates=['DiaCompra'])
    return df

def main():
    st.set_page_config(page_title='Análise RFV', layout='wide')
    st.title('Análise RFV')
    st.markdown('---')

    st.sidebar.write("## Upload de Arquivo")
    data_file = st.sidebar.file_uploader("Selecione um arquivo CSV", type=['csv'])

    if data_file is not None:
        df_compras = load_data(data_file)
        st.write("## Dados Carregados")
        st.write(df_compras.head())

        dia_atual = datetime(2021, 12, 9)
        df_recencia = df_compras.groupby(by='ID_cliente', as_index=False)['DiaCompra'].max()
        df_recencia.columns = ['ID_cliente', 'DiaUltimaCompra']
        df_recencia['Recencia'] = df_recencia['DiaUltimaCompra'].apply(lambda x: (dia_atual - x).days)
        df_recencia.drop('DiaUltimaCompra', axis=1, inplace=True)

        st.write("## Recência Calculada")
        st.write(df_recencia.head())

if __name__ == "__main__":
    main()